### ISSUE TITLE
Integrate reindent script

### ISSUE THREAD

**Issue by adam3smith** [citation-style-language/Sheldon#37]
It would be great if we could include the reindent/reorder script (that also runs the formatter) as part of an automated workflow. I see two options.

1. It could just run as part of the PR
2. It could listen for a command ("/Sheldon reorder")

I'd be happy with either option. They both have upsides

**Comment by adam3smith** [comment]
@retorquere we'd love some if your help making sure the move to 1.0.2 goes smoothly on January 1. Moreover, any chance you'd be willing to address #30 #37 and this issue? We do have some $ to pay you

**Comment by retorquere** [comment]
> It would be great if we could include the reindent/reorder script (that also runs the formatter) as part of an automated workflow. 

I don't know what this script does (or where the script is even)

> I see two options.
> 
>     1. It could just run as part of the PR
> 
>     2. It could listen for a command ("/Sheldon reorder")

Would these test something? Alter something?

> @retorquere we'd love some if your help making sure the move to 1.0.2 goes smoothly on January 1. 

Sure, no problem.

> Moreover, any chance you'd be willing to address #30 #37 and this issue?

I'm having a look, and I think I'll manage, but the cruft is really starting to accumulate in sheldon, and it sort of feels like I'm stacking kludges; during the migration to github actions I tried to make minimal changes, and part of the cruft is my own damn fault because I didn't document the changes with comments. Doesn't help that Ruby hasn't been my go-to language for a long while now, and that Ruby encourages implicit-over-explicit (like not needing to use `this` or `self` for method calls). I think we'll be fine for now, but I think a rewrite of sheldon is going to be necessary at some point. I felt that way with the last few changes but didn't want to push my personal preference.

**Comment by adam3smith** [comment]
> I don't know what this script does (or where the script is even)

The script makes sure the style is indented properly, escapes some characters, and resorts the info section. So it changes something

The JS version is here https://github.com/citation-style-language/formatter/tree/gh-pages/libraries

There is a python version, but I think it does some slightly different.

That's here https://github.com/citation-style-language/utilities/blob/master/csl-reindenting-and-info-reordering.py

**Comment by adam3smith** [comment]
> I think we'll be fine for now, but I think a rewrite of sheldon is going to be necessary at some point. I felt that way with the last few changes but didn't want to push my personal preference.

I'm OK with that, but would rather wait a couple of months post 1.0.2 so we have some breathing room and time to test.
Can you give us an informal quote on that? Anything that's more than a couple of hundred dollars should get posted to the forums prior to doing it for transparency

**Comment by retorquere** [comment]
> The script makes sure the style is indented properly, escapes some characters, and resorts the info section. So it changes something
> 
> The JS version is here https://github.com/citation-style-language/formatter/tree/gh-pages/libraries
> 
> There is a python version, but I think it does some slightly different.
> 
> That's here https://github.com/citation-style-language/utilities/blob/master/csl-reindenting-and-info-reordering.py

So which of these would you want to have ran, and when?

> I'm OK with that, but would rather wait a couple of months post 1.0.2 so we have some breathing room and time to test. Can you give us an informal quote on that? Anything that's more than a couple of hundred dollars should get posted to the forums prior to doing it for transparency

I think the current changes are manageable in the ruby version. I don't think I'd take more than a couple of hundred dollars.

WRt the port, it's not up to me to decide whether the port is deemed desirable. Strictly seen it is not required required; sheldon works as-is. It's just that it takes me more and more time to get reacquainted with how it's put together, and the way ruby works there's a lot of mental balls to keep in the air because scope in ruby is so permeable. I've been tempted to just do the port every time I make any change to sheldon.

**Comment by adam3smith** [comment]
> So which of these would you want to have ran, and when?

The JS one and I think ideally triggered by a comment, so on demand. If that's not possible, then on merge (is that possible?)

**Comment by adam3smith** [comment]
> WRt the port, it's not up to me to decide whether the port is deemed desirable

Appreciate that, but given how much we benefit from your help on it, we certainly take your opinion very seriously, and more generally, simplifying key code is good for sustainability

**Comment by retorquere** [comment]
> > So which of these would you want to have ran, and when?
> 
> The JS one and I think ideally triggered by a comment, so on demand. If that's not possible, then on merge (is that possible?)

That's possible.

**Comment by retorquere** [comment]
So would changes made by the reindent script be committed to the PR branch by sheldon?

I would have to figure out how to do that safely; cross-branch commit isn't too hard (although I'd have to figure out where the relevant info lives), but since the user can in principle add new changes to the PR while sheldon is running, there's a chance of race conditions, and handling those will be tricky. I'd probably have to re-trigger on failure to get past the race condition, but that in turn has the risk of an infinite loop.

**Comment by adam3smith** [comment]
> So would changes made by the reindent script be committed to the PR branch by sheldon?

That's what I was thinking, but I see the issue. Other ideas to achieve something similar would certainly be welcome

**Comment by retorquere** [comment]
We could apply the re-indent on merge. That's unlikely to end up with race conditions. It would also mean that follow-up edits on a PR would not force the submitter to pull back in the re-indent changes, a workflow that would probably stymie a lot of people.

**Comment by retorquere** [comment]
> Appreciate that, but given how much we benefit from your help on it, we certainly take your opinion very seriously, and more generally, simplifying key code is good for sustainability

I see a few candidates for a port:

* javascript: has the benefit that it would use the actual citeproc that zotero uses, and a language that I reckon most Zoteristas will be familiar with
* typescript: the benefits of javascript, with type-checking and a few es-next features
* python: in some cases easier to read because it doesn't assume async-first like much of the JS/TS infrastructure does these days.

**Comment by rmzelle** [comment]
> I see two options.
> 
>     1. It could just run as part of the PR
> 
>     2. It could listen for a command ("/Sheldon reorder")

Another option would be to implement a check to see if the added/modified styles conform to the reindent-script requirements, and just mark the PR as failed if they don't. This would require the submitter to fix things manually (e.g. using https://formatter.citationstyles.org/, or a script for bulk submissions).

For historic context, I first wrote https://github.com/citation-style-language/utilities/blob/master/csl-reindenting-and-info-reordering.py to clean up the style repository, and later a JavaScript version (https://github.com/citation-style-language/formatter/blob/gh-pages/libraries/style-formatter.js) for the more user-friendly CSL Style Formatter (https://formatter.citationstyles.org/). They're supposed to have the same effect. Note that the Python script is still Python 2.

For the past couple of years, we have been steering people to the CSL Style Formatter, and I generally would manually run any pull requests manually through https://formatter.citationstyles.org/ before I would merge the PR to check for and fix any formatting issues. Then I'd also every now and then run https://github.com/citation-style-language/utilities/blob/master/csl-reindenting-and-info-reordering.py on the "master" branch to fix everything that slipped through the cracks.

**Comment by rmzelle** [comment]
> We could apply the re-indent on merge. That's unlikely to end up with race conditions. It would also mean that follow-up edits on a PR would not force the submitter to pull back in the re-indent changes, a workflow that would probably stymie a lot of people.

The drawback of (only) doing reformatting on merge is that non-standardized formatted styles can be hard to review (e.g. if people edit a style and switch from space-indentation to tab-indentation, or switch up the order of the various child elements of `<info/>`).

**Comment by retorquere** [comment]
> Another option would be to implement a check to see if the added/modified styles conform to the reindent-script requirements, and just mark the PR as failed if they don't. This would require the submitter to fix things manually (e.g. using https://formatter.citationstyles.org/, or a script for bulk submissions).

This is of course a possibility, and the feedback could include "please run it through https://formatter.citationstyles.org/". This has none of the aforementioned problems.

**Comment by adam3smith** [comment]
I was hoping we could automated this for convenience: I do more reviewing on the phone currently, and using the editor is a pain. Including it as a test may work, but submitters do get frustrated by tests beyond validation failing, so I was hoping to avoid that, but see the issues with the other two options.

**Comment by retorquere** [comment]
It is still possible to do the update, but race conditions aside, re-indents are almost guaranteed to give merge conflicts if the submitter adds new commits.

One other option I *think* is possible is to create a PR-on-PR, where to PR tracks the submitter's work, and the PoP applies the re-indent. That way you can review the re-indented PoP knowing it's equivalent to the submission. But I've never done this before and I'm not actually sure whether this workflow exists in github.

**Comment by retorquere** [comment]
The PR-on-PR flow is possible but it's going to be a hassle for merging stuff I think. Every option is a compromise on one aspect or another.

**Comment by retorquere** [comment]
One other option perhaps: sheldon could apply the reindent and not commit but show the post-reindent diff as a comment on the PR, and apply it on merge. Certainly not as pleasant as reviewing actual diffs.

I think the next best option is just to apply the reindent on the PR. Submitters will have to pull back changes before they can make follow-up commits though.

**Comment by adam3smith** [comment]
> I think the next best option is just to apply the reindent on the PR. Submitters will have to pull back changes before they can make follow-up commits though.

I'd go with this. We have a very large number of submissions entirely through the web interface, and those wouldn't be affected

**Comment by retorquere** [comment]
I've made a [PR](https://github.com/citation-style-language/formatter/pull/8) that modularizes the libraries; it's not strictly required, but just overall cleaner to use in other contexts (like sheldon). Come to think of it -- I could easily add a command-line runner to that package.

**Comment by retorquere** [comment]
Yeah so that PR is actually less optional than I thought -- if we want to be running this from Sheldon, this would either require merging this PR, or applying the diff of this PR locally every time we run Sheldon.

Publishing to npmjs is a nicety -- `npm install https://github.com/citation-style-language/formatter.git` will work.

**Comment by retorquere** [comment]
This adds to the benefits of doing the rewrite in TS/JS BTW.

**Comment by retorquere** [comment]
> The JS one and I think ideally triggered by a comment, so on demand. If that's not possible, then on merge (is that possible?)

I overlooked this one. Is this still desired? This wouldn't be terribly hard to do.

**Comment by adam3smith** [comment]
> I overlooked this one. Is this still desired? This wouldn't be terribly hard to do

No -- current behavior is terrific, thanks again!

**Comment by retorquere** [comment]
> Then I'd also every now and then run https://github.com/citation-style-language/utilities/blob/master/csl-reindenting-and-info-reordering.py on the "master" branch to fix everything that slipped through the cracks.

It'd not be hard to set up an action that would run periodically on master to just run all styles through the formatter, and commit any changes, not that the formatter is npm-ified.
